GZYTDownloader/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

app/urls.py
from os import name
from django.urls import path,include
from . import views
app_name='gz'
urlpatterns = [
    path('',views.home,name='homepage'),
    path('download/',views.download,name='downloadpage'),
    path('makedownload/<resolution>',views.downloaddone,name='donedownload')
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.conf.urls import url
from django.shortcuts import redirect, render
from pytube import YouTube
import os
# Create your views here.
def home(request):
    return render(request,'home.html')

def download(request):
    global url
    url=request.GET.get('url') #1               #2
    yt=YouTube(url)  
    video=[]
    video=yt.streams.filter(progressive=True).all() 
    print("----video----")
    print(video)     
    embed_link=url.replace('.be','be.com/embed')
    embed_link1=embed_link.replace('youtube','www.youtube')
    print("----embed_link----")
    print(embed_link1)
    Title=yt.title
    context={
        'video':video,
        'embed':embed_link1,
        'title':Title
    }
    
    return render(request,'videopage.html',context)

def downloaddone(request,resolution):
    global url
    homedir=os.path.expanduser('~')
    dirs=homedir+'/Downloads'
    if request.method == 'POST':
        if (resolution=='144p' and YouTube(url).streams.get_by_resolution(resolution) == None):
            YouTube(url).streams.get_by_itag(17).download(dirs)
            return render(request,'success.html')
        else:
            YouTube(url).streams.get_by_resolution(resolution).download(dirs)
            return render(request,'success.html')
    return render(request,'errorpage.html')
    

app/templates/errorpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,600;1,600&family=Varela+Round&display=swap" rel="stylesheet">

    <style>

</style>
</head>
<body style="font-family: Montserrat;">
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <!-- <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top"> -->
        <span id="logo">&#8734;</span> 
            GZ-YouTube Downloader
        </a>
    </div>
      
</nav>

<div>
    <img src="https://user-images.githubusercontent.com/61460873/155869167-73315f9e-28b3-4de0-8949-6dba61418329.png" alt="">
    <p>Oops please reload or start from first</p>
</div>
<br><br>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GZYTDownloader</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,600;1,600&family=Varela+Round&display=swap" rel="stylesheet">
<meta property="og:title" content="Youtube Downloader - Online Youtube Video Downloader | GZYTDownloader">
<meta property="og:description" content="You can download the video by pasting links on the search">

    <style>

</style>
</head>
<body style="font-family: Montserrat;">
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <!-- <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top"> -->
        <span id="logo">&#8734;</span> 
            GZ-YouTube Downloader
        </a>
    </div>
      
</nav>
<div class="progress">
    <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
  </div>

<div class="container">
<form action="download/" method="GET">
    {% csrf_token %}
    <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Happy downloading</label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Paste the link here" name="url">
        
      </div>
      <center><button type="submit" class="btn btn-success m-3">Get video</button></center>
</form>
</div>
<br><br>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5125961553489406"
     crossorigin="anonymous"></script>
</body>
</html>

app/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GZYTDownloader</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<style>
#emoji{
    width: 90px;
    height: 90px;
}
</style>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <!-- <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top"> -->
        <span id="logo">&#8734;</span> 
            GZ-Instagram Video Downloader
        </a>
    </div>
      
</nav>
<div class="progress">
    <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">100%</div>
  </div>

<center>
    <span id="emoji">&#128516;</span>Thank you so much for use our tool
    <a href="/"><button class="btn btn-success">Click here to go back</button></a>
</center>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5125961553489406"
     crossorigin="anonymous"></script>
</body>
</html>

app/templates/videopage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GZYTDownloader</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,600;1,600&family=Varela+Round&display=swap" rel="stylesheet">

    <style>
.table{
    width: 600px;
}

@media only screen and (max-width: 600px) {
     iframe{
         width: 300px;
         height: 200px;
     }
     .table{
         width: 300px;
         margin: auto;
         text-align: center;
     }
    }
</style>
<script>
let size=document.getElementById('size')
console.log(size)
</script>
</head>
<body style="font-family:Montserrat;">
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
        <!-- <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top"> -->
        <span id="logo">&#8734;</span> 
            GZ-YouTube Downloader
        </a>
    </div>
      
</nav>
<div class="progress">
    <div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
  </div>
  <div class="embed-responsive embed-responsive-21by9">
    <center>
    <p> some video preview are not available due to YouTube's embed policy</p>
    <p>But you can download it .....</p>
    <iframe width="560"  height="315" class="embed-responsive-item m-3" src="{{embed}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </center>
</div>
<center>
<table class="table">
<thead>
    <th>Quality</th>
    <th>Size</th>
    <th>Download</th>
</thead>
{% for i in video%}
<tbody>
    <tr>
        <th>{{i.resolution}}</th>
        <th id="size">{{i.filesize}}</th>
        <th>
            <form action="{% url 'gz:donedownload' i.resolution %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-success" value="Download">
            </form>
            <!-- <button type="submit" class="btn btn-primary"><i class="fas fa-download"></i>Download</button> -->
        </th>
    </tr>
</tbody>
{% endfor %}
</table>
</center>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5125961553489406"
     crossorigin="anonymous"></script>
</body>
</html>